api_items:
    type: rest
    resource: AppBundle\Controller\ItemController

api_users:
    type: rest
    resource: AppBundle\Controller\UserController

api_login:
    type: rest
    resource: AppBundle\Controller\RestLoginController
    
api_password_management:
    type: rest
    resource: AppBundle\Controller\RestPasswordManagementController
    
api_profile:
    type: rest
    resource: AppBundle\Controller\RestProfileController

api_registration:
    type: rest
    resource: AppBundle\Controller\RestRegistrationController