fos_user:
    db_driver: orm
    firewall_name: api
    user_class: App\Entity\User
    service:
        mailer: fos_user.mailer.twig_swift    
    from_email:
        address: '%env(MAILER_USER)%'
        sender_name: '%env(SENDER_NAME)%'
