api_items:
    type: rest
    resource: App\Controller\ItemController

api_posts:
    type: rest
    resource: App\Controller\PostController

api_users:
    type: rest
    resource: App\Controller\UserController

api_login:
    type: rest
    resource: App\Controller\RestLoginController

api_login_check:
    path: /api/login_check    
    
api_password_management:
    type: rest
    resource: App\Controller\RestPasswordManagementController

api_profile:
    type: rest
    resource: App\Controller\RestProfileController

api_registration:
    type: rest
    resource: App\Controller\RestRegistrationController
          
